# Generated by Django 2.2.11 on 2020-03-27 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='create',
            name='exp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='tm',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 19, 1, 7, 418489)),
        ),
    ]
